apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore-deploy
  labels:
    app: trendify
spec:
  selector:
    matchLabels:
      app: trendify
  template:
    metadata:
      labels:
        app: trendify
    spec:
      containers:
        - name: trendstore-cont
          image: anitodevops/trendstore:latest
          ports:
            - containerPort: 3000
  replicas: 2
