apiVersion: v1
kind: Service
metadata: 
  name: trendstore-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
  labels:
    app: trendify
spec:
  type: LoadBalancer
  selector:
    app: trendify
  ports:
    - name: http
      port: 80
      targetPort: 3000
